/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sibfu.isit.nemeton.views;

import edu.sibfu.isit.nemeton.algorithms.AlgorithmBuilder;
import edu.sibfu.isit.nemeton.controllers.MainController;
import edu.sibfu.isit.nemeton.models.functions.NFunction;
import java.awt.GridLayout;
import java.util.Vector;
import java.util.stream.Stream;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import edu.sibfu.isit.nemeton.controllers.MainController.Goal;
import java.awt.Point;
import java.awt.event.KeyEvent;

/**
 *
 * @author Maximillian M.
 */
public class MainView extends javax.swing.JFrame {
    MainController ctrl;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        ctrl = new MainController(this);
        initComponents();
        algorithmsTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    public MainController getController() {
        return ctrl;
    }
    
    public void addAlgorithmBuilder(AlgorithmBuilder bldr) {
        DefaultTableModel m = (DefaultTableModel) algorithmsTable.getModel();
        m.addRow(new Object[] { true, bldr });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        functionGoalGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel_Algorithms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        algorithmsTable = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        functionCombo = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        functionLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        goalMin = new javax.swing.JRadioButton();
        goalMax = new javax.swing.JRadioButton();
        go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nemeton");
        setMinimumSize(new java.awt.Dimension(640, 480));

        jPanel_Algorithms.setBorder(javax.swing.BorderFactory.createTitledBorder("Алгоритмы"));

        algorithmsTable.setAutoCreateRowSorter(true);
        algorithmsTable.setModel(ctrl.getAlghotitmsTableModel());
        algorithmsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        algorithmsTable.getTableHeader().setReorderingAllowed(false);
        algorithmsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algorithmsTableMouseClicked(evt);
            }
        });
        algorithmsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                algorithmsTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(algorithmsTable);

        javax.swing.GroupLayout jPanel_AlgorithmsLayout = new javax.swing.GroupLayout(jPanel_Algorithms);
        jPanel_Algorithms.setLayout(jPanel_AlgorithmsLayout);
        jPanel_AlgorithmsLayout.setHorizontalGroup(
            jPanel_AlgorithmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AlgorithmsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel_AlgorithmsLayout.setVerticalGroup(
            jPanel_AlgorithmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AlgorithmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Параметры задачи"));

        jLabel1.setText("Функция: ");

        functionCombo.setModel(ctrl.getFunctionListModel());
        functionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Вид функции: ");

        functionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton1.setText("...");
        jButton1.setToolTipText("Настройки");
        jButton1.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel3.setText("Цель: ");

        functionGoalGroup.add(goalMin);
        goalMin.setSelected(true);
        goalMin.setText("min");

        functionGoalGroup.add(goalMax);
        goalMax.setText("max");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goalMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goalMax)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(functionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(functionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(goalMin)
                    .addComponent(goalMax))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {functionCombo, jButton1});

        go.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        go.setText("SOLVE");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Algorithms, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Algorithms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        Goal goal = goalMin.isSelected() 
            ? Goal.Minimize 
            : Goal.Maximize;
        // TODO: NEEDS REFACTORING!!!11
        ctrl.runAlgorithms(goal, ctrl.getFunction(functionCombo.getSelectedIndex()));
    }//GEN-LAST:event_goActionPerformed

    private void algorithmsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algorithmsTableMouseClicked
        Point p = evt.getPoint();
        int row = algorithmsTable.rowAtPoint(p);
        if (row != -1 && evt.getClickCount() == 2) {
            AlgorithmBuilder b = (AlgorithmBuilder) algorithmsTable.getValueAt(row, 1);
            showBuilderForm(b);   
        }
    }//GEN-LAST:event_algorithmsTableMouseClicked

    private void algorithmsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_algorithmsTableKeyPressed
        int keycode = evt.getKeyCode();
        int selected = algorithmsTable.getSelectedRow();
        if (selected != -1 && keycode == KeyEvent.VK_ENTER) {
            AlgorithmBuilder b = (AlgorithmBuilder) algorithmsTable.getValueAt(selected, 1);
            showBuilderForm(b);
        }
    }//GEN-LAST:event_algorithmsTableKeyPressed

    private void functionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionComboActionPerformed
        int selected = functionCombo.getSelectedIndex();
        if (selected == -1) {
            return;
        }
        NFunction f = ctrl.getFunction(selected);
        functionLabel.setText(f.getText());
    }//GEN-LAST:event_functionComboActionPerformed

    private void showBuilderForm(AlgorithmBuilder builder) {
        builder.show().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable algorithmsTable;
    private javax.swing.JComboBox<String> functionCombo;
    private javax.swing.ButtonGroup functionGoalGroup;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JButton go;
    private javax.swing.JRadioButton goalMax;
    private javax.swing.JRadioButton goalMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
