/*
 * The MIT License
 *
 * Copyright 2016 Max Balushkin.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package edu.sibfu.isit.nemeton.views;

import edu.sibfu.isit.nemeton.algorithms.AlgorithmBuilder;
import edu.sibfu.isit.nemeton.controllers.MainController;
import edu.sibfu.isit.nemeton.models.functions.NFunction;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import edu.sibfu.isit.nemeton.controllers.MainController.Goal;
import edu.sibfu.isit.nemeton.lib.Utils;
import java.awt.Point;
import java.awt.event.KeyEvent;

/**
 *
 * @author Max Balushkin
 */
public class MainView extends javax.swing.JFrame {
    MainController ctrl;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        ctrl = new MainController(this);
        initComponents();
        algorithmsTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    public MainController getController() {
        return ctrl;
    }
    
    public void addAlgorithmBuilder(AlgorithmBuilder bldr) {
        DefaultTableModel m = (DefaultTableModel) algorithmsTable.getModel();
        m.addRow(new Object[] { true, bldr });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        functionGoalGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel_Algorithms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        algorithmsTable = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        functionCombo = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        goalMin = new javax.swing.JRadioButton();
        goalMax = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        functionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        outShowSurface = new javax.swing.JCheckBox();
        outShowHistory = new javax.swing.JCheckBox();
        go = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        runsAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        analysisAccuracy = new javax.swing.JTextField();
        analyse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nemeton");
        setMinimumSize(new java.awt.Dimension(826, 771));
        setResizable(false);

        jPanel_Algorithms.setBorder(javax.swing.BorderFactory.createTitledBorder("Алгоритмы"));

        algorithmsTable.setAutoCreateRowSorter(true);
        algorithmsTable.setModel(ctrl.getAlghoritmsTableModel());
        algorithmsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        algorithmsTable.getTableHeader().setReorderingAllowed(false);
        algorithmsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algorithmsTableMouseClicked(evt);
            }
        });
        algorithmsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                algorithmsTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(algorithmsTable);

        javax.swing.GroupLayout jPanel_AlgorithmsLayout = new javax.swing.GroupLayout(jPanel_Algorithms);
        jPanel_Algorithms.setLayout(jPanel_AlgorithmsLayout);
        jPanel_AlgorithmsLayout.setHorizontalGroup(
            jPanel_AlgorithmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AlgorithmsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel_AlgorithmsLayout.setVerticalGroup(
            jPanel_AlgorithmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AlgorithmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Параметры задачи"));

        jLabel1.setText("Функция: ");

        functionCombo.setModel(ctrl.getFunctionListModel());
        functionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Вид функции: ");

        jButton1.setText("...");
        jButton1.setToolTipText("Настройки");
        jButton1.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel3.setText("Цель: ");

        functionGoalGroup.add(goalMin);
        goalMin.setSelected(true);
        goalMin.setText("min");
        goalMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalMinActionPerformed(evt);
            }
        });

        functionGoalGroup.add(goalMax);
        goalMax.setText("max");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        functionLabel.setBackground(new java.awt.Color(255, 255, 255));
        functionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(functionLabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionCombo, 0, 360, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goalMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goalMax))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(functionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(goalMin)
                    .addComponent(goalMax))
                .addGap(9, 9, 9))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {functionCombo, jButton1});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Вывод"));

        outShowSurface.setSelected(true);
        outShowSurface.setText("Отображать график функции");

        outShowHistory.setSelected(true);
        outShowHistory.setText("Отображать историю поиска");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outShowSurface)
                    .addComponent(outShowHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outShowSurface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outShowHistory))
        );

        go.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        go.setText("SOLVE");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Параметры анализа"));

        jLabel4.setText("Количество запусков: ");

        runsAmount.setText("100");

        jLabel5.setText("Точность: ");

        analysisAccuracy.setText("0.0001");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(analysisAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(runsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(analysisAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        analyse.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        analyse.setText("ANALYSE");
        analyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Algorithms, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analyse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Algorithms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analyse, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Goal getGoal() {
        return goalMin.isSelected() 
            ? Goal.Minimize 
            : Goal.Maximize;
    }
    
    public NFunction getFunction() {
        return (NFunction) functionCombo.getSelectedItem();
    }
    
    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        final Goal goal = getGoal();

        final NFunction function = getFunction();
        final boolean showSurface = outShowSurface.isSelected() && outShowSurface.isEnabled();       
        final boolean showHistory = outShowHistory.isSelected();

        ctrl.runAlgorithms( goal, function, showSurface, showHistory );
    }//GEN-LAST:event_goActionPerformed

    private void algorithmsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algorithmsTableMouseClicked
        Point p = evt.getPoint();
        int row = algorithmsTable.rowAtPoint(p);
        if (row != -1 && evt.getClickCount() == 2) {
            AlgorithmBuilder b = (AlgorithmBuilder) algorithmsTable.getValueAt(row, 1);
            showBuilderForm(b);   
        }
    }//GEN-LAST:event_algorithmsTableMouseClicked

    private void algorithmsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_algorithmsTableKeyPressed
        int keycode = evt.getKeyCode();
        int selected = algorithmsTable.getSelectedRow();
        if (selected != -1 && keycode == KeyEvent.VK_ENTER) {
            AlgorithmBuilder b = (AlgorithmBuilder) algorithmsTable.getValueAt(selected, 1);
            showBuilderForm(b);
        }
    }//GEN-LAST:event_algorithmsTableKeyPressed

    private void functionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionComboActionPerformed
        int selected = functionCombo.getSelectedIndex();
        if ( selected == -1 ) {
            return;
        }
        NFunction f = ctrl.getFunction( selected );
        functionLabel.setText( f.getText() );
        
        if ( !f.isMapped() ) {
            outShowSurface.setEnabled( false );
        } else {
            outShowSurface.setEnabled( true );
        }
    }//GEN-LAST:event_functionComboActionPerformed

    private void analyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseActionPerformed
        Goal goal = getGoal();
        NFunction function = getFunction();
        int n = Utils.intg( runsAmount.getText() );
        double accuracy = Utils.real( analysisAccuracy.getText() );
        
        ctrl.analyse( goal, function, n, accuracy );
    }//GEN-LAST:event_analyseActionPerformed

    private void goalMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goalMinActionPerformed

    private void showBuilderForm(AlgorithmBuilder builder) {
        builder.show().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable algorithmsTable;
    private javax.swing.JButton analyse;
    private javax.swing.JTextField analysisAccuracy;
    private javax.swing.JComboBox<String> functionCombo;
    private javax.swing.ButtonGroup functionGoalGroup;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JButton go;
    private javax.swing.JRadioButton goalMax;
    private javax.swing.JRadioButton goalMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox outShowHistory;
    private javax.swing.JCheckBox outShowSurface;
    private javax.swing.JTextField runsAmount;
    // End of variables declaration//GEN-END:variables
}
